### ISSUE TITLE
Incorporated in ss4-compatible forum module

### ISSUE THREAD

**Issue by sminnee** [silverstripe-archive/silverstripe-bbcodeparser#1]
This has been spun out as a module to help with the forum upgrade.

As part of that, this module will need testing.

**Comment by zanderwar** [comment]
This can likely close now with #3

**Comment by dhensby** [comment]
has it been incorporated with the forum module, yet?

**Comment by zanderwar** [comment]
Yeah, and forum tests are passing except one irrelevant to any of that
